version: "3.8"

services:

  mysql_server:
    image: mysql:8.0
    ports:
      - 3308:3308
    volumes:
      - data-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_USER=lakshan
      - MYSQL_PASSWORD=Dev@r0ot
      - MYSQL_ROOT_PASSWORD=Dev@r0ot
      - MYSQL_TCP_PORT=3308

    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql_server
    restart: always



volumes:
  data-db: